[package]
name = "rpled-compile"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "rpled-compile"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
env_logger = "0.11"
log = "0.4"
luaparse = "0.2.0"
anyhow = "1.0"

[dev-dependencies]
rstest = "0.23"
